AWSTemplateFormatVersion: "2010-09-09"

Description:
  An AWS CloudFormation template describing the Udagram service stack.

Parameters:
  EnvironmentName:
    Description:  An environment name that will be prefixed to resources
    Type: String

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      BucketName: !Sub ${EnvironmentName}-s3-bucket

  S3FileReader:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${EnvironmentName}-s3-file-reader
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        -
          PolicyName: S3FileReaderPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              -
                Effect: Allow
                Action: [ "s3:Get*", "s3:List*" ]
                Resource: "*"

Outputs:
  S3Bucket:
    Description: A reference to the created VPC
    Value: !Ref S3Bucket
    Export:
      Name: !Sub ${EnvironmentName}-s3-bucket

  S3FileReader:
    Description: A reference to the created IAM role
    Value: !Ref S3FileReader
    Export:
      Name: !Sub ${EnvironmentName}-s3-file-reader
